refactor: generic hash set
StudioSol/set pull request #8
Opened 2022-03-21 18:01 UTC by VictorAssunc

I had trouble getting the variadic parameter to work and the simplest solution I found was to change it to receive a slice.

So references like the following will not work:
 ```golang
linkedHashSet := set.NewLinkedHashSet(1, 1, 2, 2, 3, 3)
linkedHashSet.Add(1, 2, 3, 4)
linkedHashSet.Remove(0, 1, 2, 3)
```

Accepting ideas to work around it

2022-04-01 18:40 UTC, rodrigo-brito requested changes

2022-04-01 18:40 UTC, rodrigo-brito commented on linkedhashset.go
> +	constraints.Integer | constraints.Float
maybe we can use `constraints.Ordered`

2022-09-06 12:14 UTC, ftcRibeiro commented
A tentativa [desse przin](https://github.com/StudioSol/set/pull/9) deu bom.

A maior diferença foi usar o _comparable_ 🤔. Fiz o pr antes de ver que tu já tinha começado aqui 🥲

2024-07-17 14:05 UTC, VictorAssunc commented
Fixed by https://github.com/StudioSol/set/pull/9

2024-07-17 14:05 UTC, closed without merging